### ISSUE TITLE
Semantic versioning (again)

### ISSUE THREAD

**Issue by anowacki** [EarthScope/libmseed#115]
The recent [v3.0.19](https://github.com/EarthScope/libmseed/releases/tag/v3.0.19) release contains the following changes:

> - `ms3_detect()` now returns `int64_t` instead of `int`.
> - MS3Record.encoding now `int16_t` instead of `int8_t`.
> - `mstl3_unpack_recordlist()`'s `outputsize` argument is now `uint64_t` instead of `size_t`.
> - `mseh_get_ptr_r()`'s `maxlength` is now `uint32_t` instead of `size_t`.

As far as I understand it, these changes mean that programs and libraries written against v3.0.18's public API can no longer be compiled against/linked to v3.0.19.  They would have to be rewritten to work if calling `ms3_detect`.  Is that correct?

If so, then it looks to me like this is a **breaking release** per [semver](https://semver.org), meaning this should have been v4.0.0.  A bump of the patch number should only signify bug fixes.

With reference to #107 and the documented policy added in https://github.com/EarthScope/libmseed/commit/d0f350067a3082ae379984b3f60762681197c35e, could I ask whether the patch bump was intentional and your interpretation of semver is looser than perhaps a strict reading of it, or whether you might want to change this release to be a major version bump?  I appreciate you will want to manage releases your own way, but as a downstream consumer of the library some certainty is helpful.

**Comment by chad-earthscope** [comment]
My deepest apologies.  I do not have a looser definition of semantic versioning, I simply broke the rules and had temporarily forgotten how much downstream usage has already taken root.  I have retracted the v3.0.19 release and turned it into a v3.1.0 release with an large warning and a promise that the API will remain stable.  I realize that this also fails to follow semver.

The release notes contain a description of the issues encountered, in summary the v3.0.x releases cannot properly detect v3 records that fully comply with the format specification.  For this reason the v3.0.x releases will not be maintained, they are a dead end.  A major version bump is difficult for a number of reasons, one of them being the choice to add "3" to many structure and function names, which is technically OK, but adds even more cognitive confusion to the (somewhat sprawling) API that has grown over 20 years.

> They would have to be rewritten to work if calling ms3_detect. Is that correct?

Not necessarily.  The code should be adjusted to get the full range, but it will work, and most compilers will not even throw a warning because this kind of implicit cast is very common (e.g. `int length = strlen (str);` is very common even though strlen() returns size_t which is distinctly not an int).  I believe most of the changes do not effect most of the programs using the library because they are generally values and functions not directly used by the programs.  Of course the API should not have changed, I'm simply rationalizing that the effect is small adjustments for the most part.  The most effected downstream use are the language wrappers (Julia, Rust, Python), which are more sensitive to more of the API and luckily fewer in number.

Again, apologies for the breakage.  That will not happen again.

**Comment by chad-earthscope** [comment]
| They would have to be rewritten to work if calling ms3_detect. Is that correct?

To test, I compiled v3.0.17 as a shared library (on macOS so a dylib) and test program against it.  Then compiled v3.1.0 as a shared library and the binary test program worked for the most part (parsing records), but then failed on things like decoding data.  So programs should be recompiled at minimum, adjusted for new values, but definitely not shared library compatible.
