### ISSUE TITLE
Missing man pages

### ISSUE THREAD

**Issue by crish4cks** [EarthScope/libmseed#117]
Hi,
I tested the following build script with the latest version of libmseed (3.1.1) and it does not seem to create the man pages.
Is there anything I am missing?

https://slackbuilds.org/repository/15.0/libraries/libmseed/

With libmseed version 2.19.8 it worked fine.

Thank you very much,
Cristiano.

**Comment by chad-earthscope** [comment]
Hi @crish4cks,

With major new version (3), there are no longer man pages.  Instead the primary documentation is maintained online here:
https://earthscope.github.io/libmseed/

These man pages were never generated.  Instead they were manually maintained, a process that is labor intensive.  They were replaced with in-code documentation and rendered to HTML via Doxygen.  In theory, Doxygen can create man pages too.  I tried it but the pages it made are not the function names but instead the large categories in the web docs (because that's what I created the layout for).  You may wish to see if Doxygen can be tweaked to generate better man pages.  Alternatively, Doxygen can be run to generate the HTML for local viewing.
